version: "3.8"
#кринж
services:

  account:
    build:
      context: ./account
      dockerfile: /Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - postgres

  hospital:
    build:
      context: ./hospital
      dockerfile: /Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - postgres

  timetable:
    build:
      context: ./timetable
      dockerfile: /Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - db
    networks:
      - postgres

  document:
    image: "eclipse-temurin:17-jdk-jammy"
    command: "java -jar ./document/build/libs/document-0.0.1-SNAPSHOT.jar"
    ports:
      - "8084:8084"
    depends_on:
      - db
    networks:
      - postgres

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge